### Create a user
POST http://localhost:3000/users
Content-Type: application/json

{
    "name": "John Doee",
    "email": "johndoee@example.com"
}

### Create a project
POST http://localhost:3000/projects
Content-Type: application/json

{
    "title": "My first project",
    "userId": 1
}

### Create a todo
POST http://localhost:3000/todos
Content-Type: application/json

{
    "title": "My first todo",
    "userId": 1,
    "projectId": 2
}

### Authenticate
POST http://localhost:3000/authenticate
Content-Type: application/json

{
    "email": "peter@prisma.io"
}

### Authenticate from link
GET http://localhost:3000/auth-links/authenticate?code=kd7twxct5jhx92hymey2te2z&redirect=google.com.br
